// A set's RELEASE GROUP — what Scryfall's `g:` / `group:` answers — from the set catalog alone.
//
// The rule is a function of one field of Scryfall's set objects, `parent_set_code`, and of
// nothing a card carries. Measured on api.scryfall.com 2026-10-08, 58 sets over 19 families found
// in that day's `/sets` (every structural shape it holds: 289 sets with no parent and no child,
// 182 roots with children only, 48 sets whose parent has a parent of its own, under roots with
// one, two and three such branches). The seven Lorwyn Eclipsed sets were read card by card; each
// of the other 51 was proved by three requests — `g:<code>` and the `e:` list below have one
// `total_cards` under `unique=prints&include_extras=true`, and `g:<code> -(<the list>)` is a 404:
//
//   g:<code>  =  the set, its CHILDREN, its PARENT, and its parent's other children
//
// ONE STEP EACH WAY, NOT THE FAMILY. A grandchild is not a child and a grandparent is not a
// parent, so the group depends on which member is named:
//
//   g:ecl   ecl + its five children                        tecc is NOT in it (a grandchild)
//   g:tecl  the same six                                    a sibling's child is no sibling
//   g:ecc   all seven — ecc, its child tecc, its parent ecl, ecl's other four children
//   g:tecc  tecc and ecc                                    the grandparent ecl is NOT in it
//   g:pbig  pbig, big, tbig                                 not otj, and not its cousin totc
//   g:lea   lea alone                                       no parent, no child
//
// The catalog holds no set deeper than a grandchild, so nothing further could be measured; this
// reads one step from whatever set is named, which is what the three depths agree on.
//
// A set the catalog lists with NO cards still answers (`g:yfra`, an empty child, is its parent's
// group of 672), so membership is the catalog's and never the card table's — which is why the
// rule is read from the mirrored `/sets` value (reference-kv.ts) rather than from the store, and
// why it is current with the nightly publish instead of with a table generated by hand.
//
// COST: nothing for a query without the keyword. With one, the caller reads the catalog once per
// isolate and hour (reference-routes.ts) and this builds two maps over its ~1,050 sets.

/** A set code as the catalog spells one, and as it may be written into a query after `e:`. */
const CATALOG_CODE_RE = /^[0-9a-z]{1,8}$/;

/** The release groups of a set catalog. */
export interface SetGroups {
	/**
	 * The OTHER sets of the group `code` names — its children, its parent and its parent's other
	 * children — sorted. Empty for a set with no parent and no child, null for a code the catalog
	 * does not list. `code` is lower-case.
	 */
	others(code: string): readonly string[] | null;
}

/** The catalog that could not be read: every code is one it does not list. */
export const NO_SET_GROUPS: SetGroups = { others: () => null };

function catalogCode(value: unknown): string | null {
	if (typeof value !== "string") return null;
	const lower = value.toLowerCase();
	return CATALOG_CODE_RE.test(lower) ? lower : null;
}

/**
 * The groups of a parsed `/sets` `data` array, or null when it is not one or lists no set — a
 * catalog that cannot say, which the reader takes as "every code is unknown".
 *
 * A code that is not shaped like one is skipped rather than trusted: these strings are written
 * into the query the parser reads.
 */
export function setGroupsOf(sets: unknown): SetGroups | null {
	if (!Array.isArray(sets)) return null;
	const parents = new Map<string, string>();
	const children = new Map<string, string[]>();
	for (const set of sets) {
		if (typeof set !== "object" || set === null) continue;
		const code = catalogCode((set as { code?: unknown }).code);
		if (code === null) continue;
		const parent = catalogCode((set as { parent_set_code?: unknown }).parent_set_code) ?? "";
		parents.set(code, parent);
		if (parent === "") continue;
		const siblings = children.get(parent);
		if (siblings === undefined) children.set(parent, [code]);
		else siblings.push(code);
	}
	if (parents.size === 0) return null;
	return {
		others(code) {
			const parent = parents.get(code);
			if (parent === undefined) return null;
			const group = new Set(children.get(code));
			if (parent !== "") {
				group.add(parent);
				for (const sibling of children.get(parent) ?? []) group.add(sibling);
			}
			group.delete(code);
			return [...group].sort();
		},
	};
}
