// Typed access to the assets the WORKER reads: page templates it splices
// values into, the cache-busting hashes it writes into their markup, and the
// critical CSS it inlines. Generated by scripts/generate-assets.ts.
//
// Files a BROWSER fetches — app.js, app.min.js, card.js, styles.css, the
// icons, robots.txt — are NOT here. They are served straight from Cloudflare's
// CDN out of public/, so a request for one never starts an isolate. See the
// header of scripts/generate-assets.ts for the measurements that motivated the
// split; this blob went from ~313KB to ~20KB, and script size costs isolate
// startup at roughly 1.5ms per 100KB.

import rawGenerated from "./assets.gen.txt";

/**
 * Parsed on FIRST USE, not at module scope.
 *
 * A JSON import would be inlined by the bundler as an object literal that every
 * isolate materialises at startup, including the ones that only answer /search
 * and never render a page. Kept as text, those isolates never touch it.
 */
interface GeneratedAssets {
	text: Record<string, string>;
	criticalCss: string;
	hashes: Record<string, string>;
}

let parsed: GeneratedAssets | null = null;
function generated(): GeneratedAssets {
	parsed ??= JSON.parse(rawGenerated) as GeneratedAssets;
	return parsed;
}

/** A Worker-side template or fragment; an unknown name is a bug here. */
export function staticText(filename: string): string {
	const content = generated().text[filename];
	if (content === undefined) {
		throw new Error(`Unknown static asset: ${filename}`);
	}
	return content;
}

/**
 * Upstream builds this in APIResource.__init__ from styles.css. Here it is
 * precomputed at build time: it is a pure function of a vendored file, so
 * deriving it per isolate only delayed the first response.
 */
export function criticalCss(): string {
	return generated().criticalCss;
}

// Upstream _STYLES_CSS_HASH / _APP_MIN_JS_HASH / _CARD_JS_HASH
// (api_resource.py:108-110): sha256 hex prefix of the file bytes.
/**
 * A missing hash THROWS rather than falling back to "".
 *
 * `?? ""` looks harmless and is not. public/_headers serves /static/app.min.js as
 * `max-age=31536000, immutable`, and Cloudflare matches _headers on PATH, not query — so the
 * year-long immutable cache applies whether or not a version rides along. With an empty hash every
 * deploy serves the identical unversioned URL under that cache, which means a shipped JS bug is
 * unfixable for anyone who already loaded the page: their browser has no reason to ever refetch.
 *
 * That happened. assets.gen.txt went stale against this generator and lost its `hashes` key
 * entirely, and nothing failed — the site just quietly stopped being able to ship frontend fixes.
 * A build that cannot bust its own cache should not boot.
 */
function requiredHash(name: "styles.css" | "app.min.js" | "card.js"): string {
	const value = generated().hashes?.[name];
	if (!value) {
		throw new Error(
			`assets.gen.txt has no hash for ${name}. Run \`bun scripts/generate-assets.ts\` — shipping ` +
				"without it serves an unversioned URL under a one-year immutable cache.",
		);
	}
	return value;
}

export function stylesCssHash(): string {
	return requiredHash("styles.css");
}
export function appMinJsHash(): string {
	return requiredHash("app.min.js");
}
export function cardJsHash(): string {
	return requiredHash("card.js");
}

// Shared fragments (api_resource.py:117-121), read on first use rather than at
// import so /search isolates never parse the blob.
export function faviconHtml(): string {
	return staticText("fragments/favicon.html");
}
export function preconnectsHtml(): string {
	return staticText("fragments/preconnects.html");
}
export function fontsHtml(): string {
	return staticText("fragments/fonts.html");
}
export function cssHtml(): string {
	return staticText("fragments/css.html");
}
export function footerHtml(): string {
	return staticText("fragments/footer.html");
}
