// Typed access to the assets the WORKER reads: page templates it splices
// values into, the cache-busting hashes it writes into their markup, and the
// critical CSS it inlines. Generated by scripts/generate-assets.ts.
//
// Files a BROWSER fetches — app.js, app.min.js, card.js, styles.css, the
// icons, robots.txt — are NOT here. They are served straight from Cloudflare's
// CDN out of public/, so a request for one never starts an isolate. See the
// header of scripts/generate-assets.ts for the measurements that motivated the
// split; this blob went from ~313KB to ~20KB, which measured roughly 1.5ms of
// isolate startup per 100KB at the time. That rate is no longer predictive of
// new work — see the README's startup section before reasoning from it. What
// still costs is what the next comment describes: structure evaluated at
// module load, not bytes parsed.

import rawGenerated from "./assets.gen.txt";

/**
 * Parsed on FIRST USE, not at module scope.
 *
 * A JSON import would be inlined by the bundler as an object literal that every
 * isolate materialises at startup, including the ones that only answer /search
 * and never render a page. Kept as text, those isolates never touch it.
 */
interface GeneratedAssets {
	text: Record<string, string>;
	criticalCss: string;
	hashes: Record<string, string>;
	paths: Record<string, string>;
}

let parsed: GeneratedAssets | null = null;
function generated(): GeneratedAssets {
	parsed ??= JSON.parse(rawGenerated) as GeneratedAssets;
	return parsed;
}

/** A Worker-side template or fragment; an unknown name is a bug here. */
export function staticText(filename: string): string {
	const content = generated().text[filename];
	if (content === undefined) {
		throw new Error(`Unknown static asset: ${filename}`);
	}
	return content;
}

/**
 * Upstream builds this in APIResource.__init__ from styles.css. Here it is
 * precomputed at build time: it is a pure function of a vendored file, so
 * deriving it per isolate only delayed the first response.
 */
export function criticalCss(): string {
	return generated().criticalCss;
}

/** The three assets whose URLs carry a content hash. */
export type HashedAsset = "styles.css" | "app.min.js" | "card.js";

/**
 * The content-addressed path for an asset: `/static/app.<hash>.min.js`.
 *
 * A missing entry THROWS rather than falling back to the unhashed path.
 *
 * Upstream splices `?v=<hash>` onto a fixed path (api_resource.py:486-501) and can afford to: the
 * same WSGI process serves the bytes, so URL and content cannot disagree. On Workers the asset is
 * served by Cloudflare's asset layer, which resolves by PATH and ignores the query — verified
 * against the live deploy, where `?v=deadbeef0000` and `?v=` both return the current file with a
 * year-long max-age. A query-versioned URL is therefore an ALIAS for whatever object currently
 * sits at that path, not a name for specific bytes, and any window in which the deployed asset
 * lagged the deployed HTML handed clients the old file under the new key and let them pin it.
 * That is how a browser came to hold pre-fix app.min.js under ?v=2c8d03ce51b5.
 *
 * With the hash in the path, an asset store that lacks these exact bytes has no such object and
 * 404s — recoverable — instead of serving different ones. So a missing path here must be loud:
 * silently emitting the unhashed URL would restore precisely the aliasing this removed.
 */
export function assetPath(name: HashedAsset): string {
	const value = generated().paths?.[name];
	if (!value) {
		throw new Error(
			`assets.gen.txt has no hashed path for ${name}. Run \`bun scripts/generate-assets.ts\` — ` +
				"shipping without it serves an unversioned URL that cannot be cache-busted.",
		);
	}
	return value;
}

/**
 * The bare content hash, for the deploy verifier (scripts/verify-deploy.sh) and the tests, which
 * compare it against the bytes actually published. Pages use assetPath().
 */
export function assetHash(name: HashedAsset): string {
	const value = generated().hashes?.[name];
	if (!value) {
		throw new Error(`assets.gen.txt has no hash for ${name}. Run \`bun scripts/generate-assets.ts\`.`);
	}
	return value;
}

// Shared fragments (api_resource.py:117-121), read on first use rather than at
// import so /search isolates never parse the blob.
export function faviconHtml(): string {
	return staticText("fragments/favicon.html");
}
export function preconnectsHtml(): string {
	return staticText("fragments/preconnects.html");
}
export function fontsHtml(): string {
	return staticText("fragments/fonts.html");
}
export function cssHtml(): string {
	return staticText("fragments/css.html");
}
export function footerHtml(): string {
	return staticText("fragments/footer.html");
}
