// Typed access to the vendored static assets, mirroring upstream's
// module-level reads of api/static/* (api_resource.py:95-121). The JSON blob
// is generated by scripts/generate-assets.ts — see that file for why the
// assets are embedded rather than imported through wrangler `rules`.

import generated from "./assets.gen.json";

const textAssets: Record<string, string> = generated.text;
const binaryAssets: Record<string, string> = generated.binaryBase64;

/** Upstream _serve_static_file reads by filename; unknown names are a bug here (upstream would 404). */
export function staticText(filename: string): string {
	const content = textAssets[filename];
	if (content === undefined) {
		throw new Error(`Unknown static asset: ${filename}`);
	}
	return content;
}

function decodeBase64(b64: string): Uint8Array {
	const raw = atob(b64);
	const bytes = new Uint8Array(raw.length);
	for (let i = 0; i < raw.length; i++) {
		bytes[i] = raw.charCodeAt(i);
	}
	return bytes;
}

function staticBinary(filename: string): Uint8Array {
	const b64 = binaryAssets[filename];
	if (b64 === undefined) {
		throw new Error(`Unknown static asset: ${filename}`);
	}
	return decodeBase64(b64);
}

// Decoded once at module init, like upstream's import-time reads.
export const FAVICON_ICO: Uint8Array = staticBinary("favicon.ico");
export const SOCIAL_PREVIEW_WEBP: Uint8Array = staticBinary("social-preview.webp");

// Upstream _STYLES_CSS_HASH / _APP_MIN_JS_HASH / _CARD_JS_HASH
// (api_resource.py:108-110): sha256 hex prefix of the file bytes, or None when
// the file is absent. All three files exist in this port (app.min.js is built
// by generate-assets.ts), so the hashes are always strings.
export const STYLES_CSS_HASH: string = generated.hashes["styles.css"];
export const APP_MIN_JS_HASH: string = generated.hashes["app.min.js"];
export const CARD_JS_HASH: string = generated.hashes["card.js"];

// Shared fragments, read once at import time (api_resource.py:117-121).
export const FAVICON_HTML: string = staticText("fragments/favicon.html");
export const PRECONNECTS_HTML: string = staticText("fragments/preconnects.html");
export const FONTS_HTML: string = staticText("fragments/fonts.html");
export const CSS_HTML: string = staticText("fragments/css.html");
export const FOOTER_HTML: string = staticText("fragments/footer.html");
