// The tag alias map: ONE small KV value per store build, read by the Worker at query time.
//
// Scryfall's tagger keeps alternate spellings for a tag in an `aliases` field and resolves them to
// the tag before matching, so `otag:reanimate-copy` and `otag:copy-from-graveyard` select the
// same cards there. Upstream #914 reproduces that by stamping every alias into the store as an
// extra key beside the slug; this port keeps the store to canonical slugs (the stamped keys cost
// 6,252,880 bytes and a fourth KV chunk on every cold load — see TagData::oracle_aliases in
// engine/builder/src/tags.rs) and resolves the alias spelling BEFORE the match instead. This
// module is where the map the resolution needs comes from.
//
// IT SHIPS WITH THE STORE, NOT WITH THE CODE. It used to be a committed module regenerated by the
// manual import script, and that was wrong in a way nothing could see: the nightly coordinator
// rebuilds the store from fresh dumps every day and never touched the committed map, so the map
// froze on 2026-08-11 while the slugs it named kept moving. When Scryfall swapped which spelling
// of `copy-from-graveyard` is canonical, the frozen map resolved the new slug to the retired one
// and BOTH spellings returned zero — and 18 aliases added since then never resolved at all.
// Every publisher now writes the map it resolved beside the archives it resolved it for:
// the native builder to `tag-aliases.json` (seed-remote-kv.ts / seed-local-store.ts publish it),
// the wasm import via `tag_aliases_export` (the coordinator publishes it right before the
// manifest). Same dumps, same map, by construction.
//
// SHAPED LIKE THE ROUTING FILTER'S KEY on purpose (see routingFilterKey): `store:card-aliases-
// v<fmt>-<built_at>.store:0` sits inside its generation's retention family, so retention by role
// retires it with the archives it describes and no second sweep exists to be forgotten. Immutable
// per build, like the chunks, so readers cache it hard.
//
// UNLIKE THE ROUTING FILTER IT IS AWAITED. A missing routing filter costs a fan-out; a missing
// alias map costs a WRONG ANSWER (the alias spelling matches nothing), so the first request in a
// fresh isolate pays one ~70KB KV read before it parses. Every request after it reads the
// isolate's copy, and the value is colo-cached for a week.

import { EMPTY_TAG_ALIASES, type TagAliasTables } from "../parser/card-query-nodes";
import { edgeCacheUrl, readThroughEdgeCache } from "./edge-cache";
import { kvBytesMetadata } from "./kv-retention";
import { KV_VALUE_CAP_BYTES } from "./store-kv";
import type { Env, StoreManifest } from "./types";

/** The alias map of one build: `store:card-aliases-v<fmt>-<built_at>.store:0`. */
export function tagAliasesKey(formatVersion: number, builtAt: string): string {
	return `store:card-aliases-v${formatVersion}-${builtAt}.store:0`;
}

/** The alias-map key for a manifest's own generation, or null when the manifest
 * does not carry the stamps to name one. */
export function tagAliasesKeyFor(manifest: StoreManifest): string | null {
	if (!manifest.format_version || !manifest.built_at) return null;
	return tagAliasesKey(manifest.format_version, String(manifest.built_at));
}

/**
 * The value's shape: `{"oracle": {alias: slug}, "art": {alias: slug}}`, exactly what
 * `TagData::aliases_json` writes for both publishers. The two dumps are separate namespaces —
 * nothing guarantees an art alias means anything in oracle space — so they stay separate here.
 */
export interface TagAliasesJson {
	oracle: Record<string, string>;
	art: Record<string, string>;
}

/**
 * Parse a published value into the parser's tables. Throws on anything that is not the shape
 * above: a value this cannot read must be REFUSED, not half-used, because the only symptom of a
 * half-read map is a tag spelling that quietly matches nothing.
 */
export function parseTagAliasTables(json: string): TagAliasTables {
	const parsed = JSON.parse(json) as unknown;
	if (!parsed || typeof parsed !== "object") throw new Error("tag aliases: not a JSON object");
	const table = (name: "oracle" | "art"): ReadonlyMap<string, string> => {
		const map = (parsed as Record<string, unknown>)[name];
		if (!map || typeof map !== "object" || Array.isArray(map))
			throw new Error(`tag aliases: "${name}" is not an object`);
		const out = new Map<string, string>();
		for (const [alias, slug] of Object.entries(map as Record<string, unknown>)) {
			if (typeof slug !== "string") throw new Error(`tag aliases: ${name}.${alias} is not a string`);
			out.set(alias, slug);
		}
		return out;
	};
	return { oracle: table("oracle"), art: table("art") };
}

/**
 * How long an isolate's colo may serve a cached alias read. FIVE MINUTES, not the week the archive
 * chunks get: the key names its build, so a PUBLISHED value never changes — but KV caches a MISS
 * for the same TTL, and the map is the one artifact that is legitimately published late
 * (scripts/publish-tag-aliases.ts writes it for a live build the coordinator shipped without one).
 * A week-long negative left every colo that had already asked resolving no aliases until the next
 * build, and bought nothing on the positive side: the isolate keeps the parsed table for its life.
 */
const TAG_ALIASES_CACHE_TTL = 300;
/** The colo's Cache API copy of a PUBLISHED map: immutable per build, so a day only bounds lingering. */
const TAG_ALIASES_EDGE_TTL_S = 86_400;
/** How long an isolate trusts "no map published for this build" before asking KV again. */
export const ALIAS_MISS_RETRY_MS = 300_000;

/** Read a build's alias map, or null when none was published for it. Throws on a KV fault. */
export async function readTagAliases(env: Env, manifest: StoreManifest): Promise<TagAliasTables | null> {
	const key = tagAliasesKeyFor(manifest);
	if (!key) return null;
	// Through the colo's Cache API first (edge-cache.ts), like the routing filter: a metered KV read
	// per cold isolate otherwise. A miss is never stored there, so the late-publish case above still
	// resolves through KV's own short negative.
	const bytes = await readThroughEdgeCache(edgeCacheUrl(key), TAG_ALIASES_EDGE_TTL_S, async () => {
		const json = await env.STORE_KV.get(key, { type: "text", cacheTtl: TAG_ALIASES_CACHE_TTL });
		return json === null ? null : new TextEncoder().encode(json);
	});
	return bytes === null ? null : parseTagAliasTables(new TextDecoder().decode(bytes));
}

/**
 * Publish a build's alias map. Validated before the put: the publishers hand over bytes they
 * produced themselves, but the one thing worse than no map is a map the reader refuses on every
 * request. Not gated on the manifest, like the routing filter — a map for a build that never
 * publishes is a key nobody names, swept with its family.
 */
export async function writeTagAliases(env: Env, formatVersion: number, builtAt: string, json: string): Promise<void> {
	parseTagAliasTables(json);
	if (json.length > KV_VALUE_CAP_BYTES) {
		throw new Error(`tag aliases are ${json.length} bytes, over the ${KV_VALUE_CAP_BYTES} KV value cap`);
	}
	await env.STORE_KV.put(tagAliasesKey(formatVersion, builtAt), json, {
		metadata: kvBytesMetadata(new TextEncoder().encode(json).byteLength),
	});
}

/** Cached per isolate and keyed by BUILD, because the map is immutable per build — a new
 * generation is a new key, not a new value under the old one. A build with no map is remembered
 * as EMPTY so the isolate stops asking KV for it once per request. */
let aliasCache: { builtAt: string; tables: TagAliasTables; missAt: number | null } | null = null;
let aliasLoad: { builtAt: string; done: Promise<TagAliasTables> } | null = null;

/**
 * The alias tables for this request's pinned build. Awaited: see the header for why a miss here
 * is a wrong answer rather than a slower one. Never throws — a KV fault costs THIS request its
 * alias resolution (the parser falls back to the spelling as typed) and is retried by the next,
 * because a failed read must not pin an isolate to an empty map.
 */
export async function liveTagAliases(env: Env, manifest: StoreManifest): Promise<TagAliasTables> {
	const builtAt = String(manifest.built_at ?? "");
	if (!builtAt) return EMPTY_TAG_ALIASES;
	const cached = aliasCache;
	// A published table is the build's for the isolate's life; an unpublished one is re-asked after
	// ALIAS_MISS_RETRY_MS, since a late publish is exactly what the miss can be hiding.
	if (cached?.builtAt === builtAt && (cached.missAt === null || Date.now() - cached.missAt < ALIAS_MISS_RETRY_MS)) {
		return cached.tables;
	}
	if (aliasLoad?.builtAt !== builtAt) {
		const done = (async (): Promise<TagAliasTables> => {
			try {
				const tables = await readTagAliases(env, manifest);
				if (tables === null) {
					console.warn(
						`tag aliases for build ${builtAt} are not published (${tagAliasesKeyFor(manifest)}); ` +
							"alias spellings (otag:reanimate-copy for copy-from-graveyard) match nothing until a publisher writes them",
					);
					aliasCache = { builtAt, tables: EMPTY_TAG_ALIASES, missAt: Date.now() };
					return EMPTY_TAG_ALIASES;
				}
				aliasCache = { builtAt, tables, missAt: null };
				console.log(`tag aliases loaded for build ${builtAt}: ${tables.oracle.size} oracle, ${tables.art.size} art`);
				return tables;
			} catch (err) {
				console.warn(`tag aliases for build ${builtAt} could not be read (${err}); this request resolves none`);
				return EMPTY_TAG_ALIASES;
			} finally {
				if (aliasLoad?.builtAt === builtAt) aliasLoad = null;
			}
		})();
		aliasLoad = { builtAt, done };
	}
	return aliasLoad.done;
}

/** Test hook: forget the isolate's cached alias map. */
export function forgetLiveTagAliases(): void {
	aliasCache = null;
	aliasLoad = null;
}
