// Seam between the HTTP routes (src/routes/) and the wasm engine (src/engine/).
// Routes depend only on this interface; tests may inject a fake.

/** Options accepted by the engine search, mirroring upstream's pyo3 query() surface. */
export interface EngineSearchOptions {
	/**
	 * Engine-wire filter tree, PRE-SERIALIZED to its canonical JSON string by
	 * the parser's serializer. A string (not the node objects) deliberately:
	 * the tree preserves Python int/float semantics via class behavior that
	 * structured clone would strip when this crosses the DO RPC boundary.
	 */
	filterTreeJson: string;
	unique: string;
	prefer: string;
	orderby: string;
	direction: string;
	/** Upstream passes 1_000_000 for "no limit". */
	limit: number;
	/** Resolved result field names (never undefined by the time it reaches the engine). */
	fields: string[];
}

export interface EngineSearchResult {
	totalCards: number;
	/** Row objects keyed by result field name. */
	cards: Record<string, unknown>[];
}

export interface EngineCatalog {
	/** Card type → count, as the engine reports it (pre-alias massaging). */
	types: Record<string, number>;
	keywords: Record<string, number>;
}

/**
 * What the routes need from an engine. Async because the engine may be local
 * (warm isolate: wasm call, resolves immediately) or remote (cold isolate:
 * RPC to the regional SearchEngine Durable Object while this isolate warms
 * itself in the background).
 */
export interface Engine {
	search(opts: EngineSearchOptions): Promise<EngineSearchResult>;
	commonCardTypes(): Promise<Record<string, number>>;
	commonCardKeywords(): Promise<Record<string, number>>;
	/** Random preferred-printing sample, mirroring upstream sample_preferred(). */
	samplePreferred(numCards: number, fields: string[]): Promise<Record<string, unknown>[]>;
	/** Number of cards in the store; 0 means "not loaded" upstream — here a loaded engine is never empty. */
	size(): Promise<number>;
}

/**
 * Thrown when the engine cannot answer. Routes translate this to a loud
 * structured error — NEVER an empty result (upstream would fall back to SQL
 * here; this deployment has no SQL by design).
 */
export class EngineUnavailableError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "EngineUnavailableError";
	}
}

export interface StoreManifest {
	store_key: string;
	built_at: string;
	card_count: number;
	printing_count: number;
	upstream_commit: string;
	format_version: number;
	/** Uncompressed archive size; the wasm buffer is preallocated from this. */
	store_bytes: number;
	/** Chunk rows the store occupies in D1 (readers validate continuity by seq). */
	chunk_count?: number;
	/**
	 * Ordered content hashes of this store's chunks (see store-chunks.ts).
	 * Present on every store published by the content-addressed path; ABSENT on
	 * stores written by the older seq-indexed publisher, which readers still
	 * have to load — a deploy that skips the import leaves yesterday's manifest
	 * in place under today's Worker.
	 */
	chunks?: string[];
	/**
	 * Scryfall's `updated_at` for the bulk dump this store was built from. Lets
	 * a deploy ask "has upstream actually changed?" instead of guessing from
	 * the store's own age. Absent on stores built before it was recorded.
	 */
	source_updated_at?: string;
}

// Generated by `bun run cf-typegen` (wrangler types) from wrangler.jsonc +
// .env — bindings, vars, and secret names all come from the real config.
export type Env = Cloudflare.Env;
