// Regenerate src/engine/colos.gen.ts — every Cloudflare location (colo) with its coordinates,
// country and Cloudflare's region name — from Cloudflare's own speed-test endpoint (backlog p4).
//
//   bun scripts/gen-colo-table.ts           write the table
//   bun scripts/gen-colo-table.ts --check   exit 1 if the published list differs (platform-drift CI)
//
// speed.cloudflare.com/locations is first-party but undocumented: it answers 403 without a
// Referer of https://speed.cloudflare.com/. The weekly check says so if that ever changes.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT = join(import.meta.dir, "..", "src", "engine", "colos.gen.ts");
const REGION_CODES: Record<string, string> = {
	"North America": "NA",
	"South America": "SA",
	Europe: "EU",
	Africa: "AF",
	"Middle East": "ME",
	"Asia Pacific": "AP",
	Oceania: "OC",
};

interface Location {
	iata: string;
	lat: number;
	lon: number;
	cca2: string;
	region: string;
}

const res = await fetch("https://speed.cloudflare.com/locations", {
	headers: { Referer: "https://speed.cloudflare.com/" },
});
if (!res.ok) {
	console.error(`::error::speed.cloudflare.com/locations answered ${res.status}`);
	process.exit(1);
}
const locations = ((await res.json()) as Location[]).slice().sort((a, b) => a.iata.localeCompare(b.iata));
const unknown = [...new Set(locations.map((l) => l.region))].filter((r) => !(r in REGION_CODES));
if (unknown.length) {
	console.error(`::error::unknown Cloudflare region name(s): ${unknown.join(", ")} — map them in gen-colo-table.ts`);
	process.exit(1);
}

const round = (n: number) => Math.round(n * 100) / 100;
const rows = locations.map(
	(l) => `\t${l.iata}: [${round(l.lat)}, ${round(l.lon)}, "${l.cca2}", "${REGION_CODES[l.region]}"],`,
);
const body = `// GENERATED by scripts/gen-colo-table.ts from https://speed.cloudflare.com/locations — do not edit.
// ${locations.length} Cloudflare locations: IATA code → [latitude, longitude, country (ISO 3166-1
// alpha-2), Cloudflare region]. Region codes: NA North America, SA South America, EU Europe,
// AF Africa, ME Middle East, AP Asia Pacific, OC Oceania. Coordinates rounded to 0.01°.

export type ColoRegion = "NA" | "SA" | "EU" | "AF" | "ME" | "AP" | "OC";

export const COLOS: Record<string, readonly [lat: number, lon: number, country: string, region: ColoRegion]> = {
${rows.join("\n")}
};
`;

if (process.argv.includes("--check")) {
	const current = readFileSync(OUT, "utf-8");
	if (current !== body) {
		console.error("::error::Cloudflare's location list changed — run `bun scripts/gen-colo-table.ts` and commit");
		process.exit(1);
	}
	console.log(`colo table current (${locations.length} locations)`);
} else {
	writeFileSync(OUT, body);
	console.log(`wrote ${OUT} (${locations.length} locations, ${body.length} bytes)`);
}
