// Regenerates the served static assets from the vendored upstream ones
// (vendor/sylvan_librarian/api/static). Run with:
//
//   bun scripts/generate-assets.ts
//
// Re-run whenever scripts/sync-upstream.sh updates anything under api/static.
//
// TWO outputs, split by who reads the file:
//
//   public/            files a BROWSER fetches, served straight from
//                      Cloudflare's CDN. These never enter the Worker script
//                      and never invoke the Worker at all.
//   src/routes/        the handful of fragments the Worker itself splices into
//     assets.gen.txt   page HTML, plus the cache-busting hashes.
//
// The split is a cold-start fix, measured. Everything used to be one ~313KB
// text module inside the script, and script size costs isolate startup at
// about 1.5ms per 100KB — which every /search paid, because at this traffic
// isolates rarely survive between requests:
//
//   blob in script   313KB -> 10,12,13ms startup   149KB -> 10,9ms
//                    0.5KB -> 7,7ms               (empty Worker floor: 5ms)
//
// Only ~17KB is genuinely Worker-side, so the rest moves to the CDN.
//
// app.min.js still does not exist upstream — their makefile builds it with
// `npx terser api/static/app.js --compress --mangle` — and the
// _STYLES_CSS_HASH/_APP_MIN_JS_HASH/_CARD_JS_HASH cache-busting hashes are
// still sha256 hex prefixes of file bytes, computed here at build time because
// a Worker has no process start to compute them at.

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { minify } from "terser";
import { buildCriticalCss } from "../src/routes/critical-css";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const staticDir = join(repoRoot, "vendor/sylvan_librarian/api/static");
const fragmentsDir = join(staticDir, "fragments");
const outPath = join(repoRoot, "src/routes/assets.gen.txt");
const publicDir = join(repoRoot, "public");

function text(path: string): string {
	return readFileSync(path, "utf8");
}

/** Mirrors upstream _static_hash: sha256 of the file bytes, first 12 hex chars. */
function hash12(bytes: Uint8Array | string): string {
	const hasher = new Bun.CryptoHasher("sha256");
	hasher.update(bytes);
	return hasher.digest("hex").slice(0, 12);
}

const appJs = text(join(staticDir, "app.js"));
// Upstream: `npx terser api/static/app.js --compress --mangle --output api/static/app.min.js`
// (makefile target api/static/app.min.js). --compress/--mangle with no options
// map to `{ compress: {}, mangle: {} }` here.
const minified = await minify(appJs, { compress: {}, mangle: {} });
if (typeof minified.code !== "string") {
	throw new Error("terser produced no output for app.js");
}
const appMinJs = minified.code;

// ── CDN assets ───────────────────────────────────────────────────────────────
//
// Written at the path a browser requests them from, so Cloudflare's asset
// worker matches the URL and serves the file WITHOUT invoking this Worker: no
// isolate start, no CPU, no request against the Worker's own budget.

/** [file inside public/, source path] */
const cdnAssets: [string, string][] = [
	["static/app.js", join(staticDir, "app.js")],
	["static/card.js", join(staticDir, "card.js")],
	["static/styles.css", join(staticDir, "styles.css")],
	["static/favicon.ico", join(staticDir, "favicon.ico")],
	["static/social-preview.webp", join(staticDir, "social-preview.webp")],
	// Upstream serves the icon from the root as well.
	["favicon.ico", join(staticDir, "favicon.ico")],
	["robots.txt", join(staticDir, "robots.txt")],
	["prefer_score_tuner.html", join(staticDir, "prefer_score_tuner.html")],
];

// Cache lifetimes, chosen for this deployment rather than copied from
// upstream: the two files whose URLs the pages cache-bust with a content hash
// can be held for a long time, and the rest for a day. Content types come from
// the platform's own extension mapping.
//
// Deliberately NOT `immutable`, which was here and caused a real outage. `immutable` means "never
// revalidate, not even on an explicit reload", so a browser that once stored the wrong bytes under
// a hashed URL keeps them for the full year with no recovery short of clearing site data. That is
// not hypothetical: a deploy updates the Worker (and so the HTML's ?v=) and the CDN assets
// separately, so a request landing between the two fetches the NEW url and gets the OLD file — and
// then pins it. Upstream sends a plain max-age for exactly this reason.
//
// Without `immutable` the long max-age still keeps normal navigation off the network; a reload
// revalidates, which is the property that makes a bad deploy recoverable by the user rather than
// by support instructions.
const HEADERS = `# GENERATED by scripts/generate-assets.ts - do not edit.
/static/app.min.js
  Cache-Control: public, max-age=31536000
/static/styles.css
  Cache-Control: public, max-age=31536000
/static/card.js
  Cache-Control: public, max-age=86400
/static/app.js
  Cache-Control: public, max-age=86400
/static/social-preview.webp
  Cache-Control: public, max-age=2592000
/static/favicon.ico
  Cache-Control: public, max-age=604800
/favicon.ico
  Cache-Control: public, max-age=604800
/robots.txt
  Cache-Control: public, max-age=86400
`;

rmSync(publicDir, { recursive: true, force: true });
for (const [name, source] of cdnAssets) {
	const dest = join(publicDir, name);
	mkdirSync(dirname(dest), { recursive: true });
	writeFileSync(dest, readFileSync(source));
}
// Built here, so it has no source file to copy.
mkdirSync(join(publicDir, "static"), { recursive: true });
writeFileSync(join(publicDir, "static/app.min.js"), appMinJs);
writeFileSync(join(publicDir, "_headers"), HEADERS);

// ── Worker-side fragments ────────────────────────────────────────────────────
//
// What is left is only what the WORKER reads: the page templates it splices
// values into, and the cache-busting hashes it writes into their markup.

const out = {
	comment: "GENERATED FILE - do not edit. Built by scripts/generate-assets.ts from vendor/sylvan_librarian/api/static.",
	text: {
		"index.html": text(join(staticDir, "index.html")),
		"card.html": text(join(staticDir, "card.html")),
		"fragments/favicon.html": text(join(fragmentsDir, "favicon.html")),
		"fragments/preconnects.html": text(join(fragmentsDir, "preconnects.html")),
		"fragments/fonts.html": text(join(fragmentsDir, "fonts.html")),
		"fragments/css.html": text(join(fragmentsDir, "css.html")),
		"fragments/footer.html": text(join(fragmentsDir, "footer.html")),
	},
	// Upstream builds this in APIResource.__init__ from styles.css, and this
	// port used to redo it at module init — which meant every isolate carried
	// the whole 17KB stylesheet AND re-derived the same string before it could
	// serve anything. It is a pure function of a file that only changes when
	// upstream does, so it belongs here.
	criticalCss: buildCriticalCss(text(join(staticDir, "styles.css"))),
	// Upstream computes these at import time from the files on disk
	// (api_resource.py _static_hash). app.min.js hashes the terser output above,
	// exactly as upstream hashes the terser output the makefile wrote to disk.
	hashes: {
		"styles.css": hash12(readFileSync(join(staticDir, "styles.css"))),
		"app.min.js": hash12(appMinJs),
		"card.js": hash12(readFileSync(join(staticDir, "card.js"))),
	},
};

// Emitted as TEXT, not as a JSON module, and compact rather than indented: a
// JSON import is inlined by the bundler as an object literal that every isolate
// materialises at startup. Small now that the browser files live on the CDN,
// but the property still holds.
writeFileSync(outPath, JSON.stringify(out));
console.log(`Wrote ${outPath} (${(JSON.stringify(out).length / 1024).toFixed(1)} KiB, was ~313 KiB)`);
console.log(`Wrote ${publicDir}/ (${cdnAssets.length + 1} CDN assets + _headers)`);
console.log(`hashes: ${JSON.stringify(out.hashes)}`);
