/**
 * Fixture parity: for every query in the exported corpus, the TS parser must
 * produce a byte-identical canonical JSON tree — or the identical error
 * message — to the Python production parser (parse_scryfall_query + to_json).
 *
 * Fixtures are generated by scripts/export-parser-fixtures.py. Any
 * disagreement is a bug in the TS port; never patch the fixture.
 */

import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { canonicalStringify, ParseError, parseScryfallQuery } from "../../src/parser";

interface FixtureCase {
	query: string;
	tree?: string;
	error?: { type: string; message: string };
}

const FIXTURES_DIR = join(import.meta.dir, "fixtures");

// tag-slugs.json lives here because the same exporter writes it, but it holds slugify cases
// rather than query/tree pairs — see tag-slugs.test.ts.
const fixtureFiles = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith(".json") && f !== "tag-slugs.json");

test("fixture corpus is present and substantial", () => {
	expect(fixtureFiles.length).toBeGreaterThan(0);
	const total = fixtureFiles
		.map((f) => (JSON.parse(readFileSync(join(FIXTURES_DIR, f), "utf-8")) as FixtureCase[]).length)
		.reduce((a, b) => a + b, 0);
	expect(total).toBeGreaterThan(500);
});

for (const file of fixtureFiles) {
	const cases = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[];
	describe(file, () => {
		for (const fixture of cases) {
			test(`parses ${JSON.stringify(fixture.query)} identically`, () => {
				if (fixture.tree !== undefined) {
					const tree = parseScryfallQuery(fixture.query);
					expect(canonicalStringify(tree)).toBe(fixture.tree);
				} else if (fixture.error !== undefined) {
					// Python surfaces every failure as ValueError; the port surfaces
					// ParseError with the identical message.
					expect(fixture.error.type).toBe("ValueError");
					let thrown: unknown;
					try {
						parseScryfallQuery(fixture.query);
					} catch (exc) {
						thrown = exc;
					}
					expect(thrown).toBeInstanceOf(ParseError);
					expect((thrown as ParseError).message).toBe(fixture.error.message);
				} else {
					throw new Error(`fixture entry for ${JSON.stringify(fixture.query)} has neither tree nor error`);
				}
			});
		}
	});
}
