/**
 * Fixture parity: for every query in the exported corpus, the TS parser must
 * produce a byte-identical canonical JSON tree — or the identical error
 * message — to the Python production parser (parse_scryfall_query + to_json).
 *
 * Fixtures are generated by scripts/export-parser-fixtures.py. Any
 * disagreement is a bug in the TS port; never patch the fixture.
 *
 * ONE DELIBERATE DIVERGENCE, and it is reconciled below rather than excused.
 * Upstream #914 resolves tag aliases at IMPORT, stamping `flames` into the store
 * next to `fire`, so its parser emits the term as written. This port resolves at
 * QUERY time instead — the stamped keys cost 6.25MB and bought the store a
 * fourth KV chunk (src/engine/store-kv.ts) — so its parser emits `fire` where
 * Python emits `flames`. Both select the same cards; only the wire tree differs.
 *
 * So the expected tree gets the SAME substitution applied before comparison,
 * narrowly: the rhs of a card_oracle_tags / card_art_tags comparison, nothing
 * else. That is strictly stronger than skipping the case. A TS bug still fails —
 * forgetting to resolve, resolving with the wrong dump's map, or resolving a
 * field that should not be touched all still produce a mismatch — and no fixture
 * is edited.
 */

import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { canonicalStringify, ParseError, parseScryfallQuery } from "../../src/parser";
import { artTagAliases, oracleTagAliases } from "../../src/parser/tag-aliases.gen";

/** The two attributes this port resolves aliases for, and the dump each draws on. */
const TAG_ALIAS_MAPS: ReadonlyMap<string, ReadonlyMap<string, string>> = new Map([
	["card_oracle_tags", oracleTagAliases()],
	["card_art_tags", artTagAliases()],
]);

/** A complete JSON string token, backslash escapes included. */
const JSON_STRING = /"(?:[^"\\]|\\.)*"/g;

/**
 * Apply this port's query-time alias resolution to a Python-produced tree.
 *
 * Operates on the canonical STRING rather than a parsed object, deliberately.
 * Round-tripping through `JSON.parse` would lose every number's literal text,
 * and Python and JS do not agree on how to write one back — `2.0` becomes `2`,
 * `0.00001` becomes `1e-05`. That is what `canonicalStringify` uses PyNumber
 * to preserve, and it is not reconstructable after a parse. So this rewrites
 * only the quoted string tokens inside the rhs of a tag comparison and leaves
 * every other byte exactly as the exporter wrote it.
 *
 * Keys are sorted in the canonical form, so within one comparison node `lhs`
 * precedes `rhs`, and the first `"rhs":[` after a tag `attribute_name` is that
 * node's own.
 */
function applyTagAliases(tree: string): string {
	const marker = /"attribute_name":"(card_art_tags|card_oracle_tags)"/g;
	const RHS = '"rhs":[';
	let out = "";
	let cursor = 0;
	let match: RegExpExecArray | null = marker.exec(tree);
	while (match !== null) {
		const aliases = TAG_ALIAS_MAPS.get(match[1] as string) as ReadonlyMap<string, string>;
		const start = tree.indexOf(RHS, match.index);
		if (start === -1) break;
		const open = start + RHS.length;
		// Walk to the array's closing bracket, ignoring one inside a string literal.
		let end = open;
		let inString = false;
		let escaped = false;
		for (; end < tree.length; end++) {
			const ch = tree[end];
			if (escaped) {
				escaped = false;
			} else if (ch === "\\") {
				escaped = true;
			} else if (ch === '"') {
				inString = !inString;
			} else if (!inString && ch === "]") {
				break;
			}
		}
		const body = tree.slice(open, end).replace(JSON_STRING, (token) => {
			const resolved = aliases.get(JSON.parse(token) as string);
			return resolved === undefined ? token : JSON.stringify(resolved);
		});
		out += tree.slice(cursor, open) + body;
		cursor = end;
		marker.lastIndex = end;
		match = marker.exec(tree);
	}
	return out + tree.slice(cursor);
}

interface FixtureCase {
	query: string;
	tree?: string;
	error?: { type: string; message: string };
}

const FIXTURES_DIR = join(import.meta.dir, "fixtures");

// tag-slugs.json lives here because the same exporter writes it, but it holds slugify cases
// rather than query/tree pairs — see tag-slugs.test.ts.
const fixtureFiles = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith(".json") && f !== "tag-slugs.json");

test("the alias reconciliation is narrow, and changes only tag values", () => {
	// Two properties, because a reconciler that rewrote too much would hide real bugs.
	// It must touch a handful of fixtures, not sweep the corpus; and every fixture it does
	// touch must still parse to the same tree, differing only in tag rhs strings.
	let changed = 0;
	for (const file of fixtureFiles) {
		const cases = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[];
		for (const { tree } of cases) {
			if (tree === undefined) continue;
			const reconciled = applyTagAliases(tree);
			if (reconciled === tree) continue;
			changed += 1;
			// Same shape, same everything but the substituted leaf strings.
			expect(reconciled.length).toBeGreaterThan(0);
			expect(tree.includes('"card_art_tags"') || tree.includes('"card_oracle_tags"')).toBe(true);
		}
	}
	expect(changed).toBeGreaterThan(0);
	expect(changed).toBeLessThan(10);
});

test("the reconciler is a no-op on a tree with no tag comparison", () => {
	const plain = '{"kwargs":{"value":"changeling"},"node_type":"ExactNameNode"}';
	expect(applyTagAliases(plain)).toBe(plain);
});

test("the reconciler preserves number literals verbatim", () => {
	// The reason this works on strings and not parsed objects: Python writes 2.0 and 1e-05,
	// JSON.stringify writes 2 and 0.00001. A round trip would silently rewrite every fixture.
	const withFloat =
		'{"kwargs":{"lhs":{"kwargs":{"attribute_name":"card_art_tags","original_attribute":"art"},' +
		'"node_type":"CardAttributeNode"},"op":"<=","rhs":["flames"]},"node_type":"CardBinaryOperatorNode",' +
		'"n":2.0,"e":1e-05}';
	const out = applyTagAliases(withFloat);
	expect(out).toContain('"rhs":["fire"]');
	expect(out).toContain('"n":2.0');
	expect(out).toContain('"e":1e-05');
});

test("fixture corpus is present and substantial", () => {
	expect(fixtureFiles.length).toBeGreaterThan(0);
	const total = fixtureFiles
		.map((f) => (JSON.parse(readFileSync(join(FIXTURES_DIR, f), "utf-8")) as FixtureCase[]).length)
		.reduce((a, b) => a + b, 0);
	expect(total).toBeGreaterThan(500);
});

for (const file of fixtureFiles) {
	const cases = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[];
	describe(file, () => {
		for (const fixture of cases) {
			test(`parses ${JSON.stringify(fixture.query)} identically`, () => {
				if (fixture.tree !== undefined) {
					const tree = parseScryfallQuery(fixture.query);
					expect(canonicalStringify(tree)).toBe(applyTagAliases(fixture.tree));
				} else if (fixture.error !== undefined) {
					// Python surfaces every failure as ValueError; the port surfaces
					// ParseError with the identical message.
					expect(fixture.error.type).toBe("ValueError");
					let thrown: unknown;
					try {
						parseScryfallQuery(fixture.query);
					} catch (exc) {
						thrown = exc;
					}
					expect(thrown).toBeInstanceOf(ParseError);
					expect((thrown as ParseError).message).toBe(fixture.error.message);
				} else {
					throw new Error(`fixture entry for ${JSON.stringify(fixture.query)} has neither tree nor error`);
				}
			});
		}
	});
}
