/**
 * Fixture parity: for every query in the exported corpus, the TS parser must
 * produce a byte-identical canonical JSON tree — or the identical error
 * message — to the Python production parser (parse_scryfall_query + to_json).
 *
 * Fixtures are generated by scripts/export-parser-fixtures.py. Any
 * disagreement is a bug in the TS port; never patch the fixture.
 *
 * ONE DELIBERATE DIVERGENCE, and it is reconciled below rather than excused.
 * Upstream #914 resolves tag aliases at IMPORT, stamping `flames` into the store
 * next to `fire`, so its parser emits the term as written. This port resolves at
 * QUERY time instead — the stamped keys cost 6.25MB and bought the store a
 * fourth KV chunk (src/engine/store-kv.ts) — so its parser emits `fire` where
 * Python emits `flames`. Both select the same cards; only the wire tree differs.
 *
 * So the expected tree gets the SAME substitution applied before comparison,
 * narrowly: the rhs of a card_oracle_tags / card_art_tags comparison, nothing
 * else. That is strictly stronger than skipping the case. A TS bug still fails —
 * forgetting to resolve, resolving with the wrong dump's map, or resolving a
 * field that should not be touched all still produce a mismatch — and no fixture
 * is edited.
 */

import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parseTagAliasTables } from "../../src/engine/tag-aliases";
import {
	canonicalStringify,
	InvalidRegexPatternError,
	ParseError,
	parseScryfallQuery,
	QueryBudgetExceeded,
} from "../../src/parser";
import { pyFloatRepr } from "../../src/parser/pystr";

/**
 * A builder sidecar (src/engine/tag-aliases.ts), handed to the parse the way the route hands it
 * the live build's. Python resolves nothing (upstream stamps aliases into the store instead), so
 * the same map is applied to its trees below.
 */
const TAG_ALIASES = parseTagAliasTables(readFileSync(join(__dirname, "../fixtures/tag-aliases.json"), "utf8"));

/** The two attributes this port resolves aliases for, and the dump each draws on. */
const TAG_ALIAS_MAPS: ReadonlyMap<string, ReadonlyMap<string, string>> = new Map([
	["card_oracle_tags", TAG_ALIASES.oracle],
	["card_art_tags", TAG_ALIASES.art],
]);

/** A complete JSON string token, backslash escapes included. */
const JSON_STRING = /"(?:[^"\\]|\\.)*"/g;

/**
 * Apply this port's query-time alias resolution to a Python-produced tree.
 *
 * Operates on the canonical STRING rather than a parsed object, deliberately.
 * Round-tripping through `JSON.parse` would lose every number's literal text,
 * and Python and JS do not agree on how to write one back — `2.0` becomes `2`,
 * `0.00001` becomes `1e-05`. That is what `canonicalStringify` uses PyNumber
 * to preserve, and it is not reconstructable after a parse. So this rewrites
 * only the quoted string tokens inside the rhs of a tag comparison and leaves
 * every other byte exactly as the exporter wrote it.
 *
 * Keys are sorted in the canonical form, so within one comparison node `lhs`
 * precedes `rhs`, and the first `"rhs":[` after a tag `attribute_name` is that
 * node's own.
 */
function applyTagAliases(tree: string): string {
	const marker = /"attribute_name":"(card_art_tags|card_oracle_tags)"/g;
	const RHS = '"rhs":[';
	let out = "";
	let cursor = 0;
	let match: RegExpExecArray | null = marker.exec(tree);
	while (match !== null) {
		const aliases = TAG_ALIAS_MAPS.get(match[1] as string) as ReadonlyMap<string, string>;
		const start = tree.indexOf(RHS, match.index);
		if (start === -1) break;
		const open = start + RHS.length;
		// Walk to the array's closing bracket, ignoring one inside a string literal.
		let end = open;
		let inString = false;
		let escaped = false;
		for (; end < tree.length; end++) {
			const ch = tree[end];
			if (escaped) {
				escaped = false;
			} else if (ch === "\\") {
				escaped = true;
			} else if (ch === '"') {
				inString = !inString;
			} else if (!inString && ch === "]") {
				break;
			}
		}
		const body = tree.slice(open, end).replace(JSON_STRING, (token) => {
			const resolved = aliases.get(JSON.parse(token) as string);
			return resolved === undefined ? token : JSON.stringify(resolved);
		});
		out += tree.slice(cursor, open) + body;
		cursor = end;
		marker.lastIndex = end;
		match = marker.exec(tree);
	}
	return out + tree.slice(cursor);
}

/**
 * ONE MORE DIVERGENCE, PORT-ONLY, and reconciled the same way. The vendored Python still rewrites
 * `is:funny` to `st:funny` — the mapping this port carried upstream with the `st:` operator — and
 * this port stopped doing so on 2026-09-08, because Scryfall's `is:funny` is a class of the
 * PRINTING (never legal, and funny-set OR playtest OR silver-bordered OR acorn-stamped, not a
 * token set) that no set-type term can reach: `t:conspiracy -is:funny` answered 27 here against
 * 25 there, the two being mb2 playtest cards in a `masters` set. It is a stored tag now
 * (`FUNNY_IS_TAG`), so the port emits `card_is_tags: ["funny"]` where the exporter, which runs the
 * vendored parser, writes the set-type tree.
 *
 * The expected tree is REPLACED by the port's own, spelled out in full, so the assertion stays a
 * byte comparison against an explicit expectation rather than a skip. Two guards keep the entry
 * honest: the query must still be in the corpus (else the entry is stale), and the exporter's tree
 * must still DIFFER from it (the day the vendored Python stores the tag too, this entry is dead
 * and must go — the fixture takes over).
 */
const PORT_ONLY_TREES: ReadonlyMap<string, string> = new Map([
	[
		"is:funny",
		'{"kwargs":{"lhs":{"kwargs":{"attribute_name":"card_is_tags","original_attribute":"is"},' +
			'"node_type":"CardAttributeNode"},"op":":","rhs":["funny"]},"node_type":"CardBinaryOperatorNode"}',
	],
]);

/**
 * A THIRD DIVERGENCE, PORT-ONLY: a number inside a text value keeps its SPELLING here. The lexer
 * hands a hyphenated value over in pieces, and a bare-digit piece is a NUMBER token; the vendored
 * hand_parser.py glues `str(tok.value)`, so `0796` came back `796` and `oracleid:9afd8f12-0796-…`
 * searched an id that does not exist (a 404 where api.scryfall.com answers Doubling Cube's four
 * printings, 2026-09-25). The port glues the token's source text (parser.ts `textOf`).
 *
 * The exporter's tree cannot be mapped forward (the zeros are gone from it), so the PORT'S tree is
 * mapped back: every hyphen-separated piece of a string that is a bare number is re-spelled the
 * way Python's `str(int)` / `repr(float)` would. Applied only when the trees differ, so a fixture
 * the port already matches is compared byte for byte; and `the number-spelling reconciliation is
 * narrow` below pins which fixtures take this path.
 */
function pythonNumberSpelling(tree: string): string {
	return tree.replace(JSON_STRING, (token) => {
		const text = JSON.parse(token) as string;
		const glued = text
			.split("-")
			.map((piece) =>
				/^[0-9]+$/.test(piece)
					? BigInt(piece).toString()
					: /^[0-9]+\.[0-9]+$/.test(piece)
						? pyFloatRepr(Number(piece))
						: piece,
			)
			.join("-");
		return glued === text ? token : JSON.stringify(glued);
	});
}

/** A number spelled in a way `str(int)` / `repr(float)` does not write back: `007`, `02`, `1.50`. */
const RESPELLED_NUMBER = /(?:^|[^0-9.])(?:0[0-9]|[0-9]+\.[0-9]*0(?![0-9]))/;

interface FixtureCase {
	query: string;
	tree?: string;
	error?: { type: string; message: string };
}

const FIXTURES_DIR = join(import.meta.dir, "fixtures");

// tag-slugs.json lives here because the same exporter writes it, but it holds slugify cases
// rather than query/tree pairs — see tag-slugs.test.ts.
const fixtureFiles = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith(".json") && f !== "tag-slugs.json");

test("the alias reconciliation is narrow, and changes only tag values", () => {
	// Two properties, because a reconciler that rewrote too much would hide real bugs.
	// It must touch a handful of fixtures, not sweep the corpus; and every fixture it does
	// touch must still parse to the same tree, differing only in tag rhs strings.
	let changed = 0;
	for (const file of fixtureFiles) {
		const cases = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[];
		for (const { tree } of cases) {
			if (tree === undefined) continue;
			const reconciled = applyTagAliases(tree);
			if (reconciled === tree) continue;
			changed += 1;
			// Same shape, same everything but the substituted leaf strings.
			expect(reconciled.length).toBeGreaterThan(0);
			expect(tree.includes('"card_art_tags"') || tree.includes('"card_oracle_tags"')).toBe(true);
		}
	}
	expect(changed).toBeGreaterThan(0);
	expect(changed).toBeLessThan(10);
});

test("the reconciler is a no-op on a tree with no tag comparison", () => {
	const plain = '{"kwargs":{"value":"changeling"},"node_type":"ExactNameNode"}';
	expect(applyTagAliases(plain)).toBe(plain);
});

test("the reconciler preserves number literals verbatim", () => {
	// The reason this works on strings and not parsed objects: Python writes 2.0 and 1e-05,
	// JSON.stringify writes 2 and 0.00001. A round trip would silently rewrite every fixture.
	const withFloat =
		'{"kwargs":{"lhs":{"kwargs":{"attribute_name":"card_art_tags","original_attribute":"art"},' +
		'"node_type":"CardAttributeNode"},"op":"<=","rhs":["flames"]},"node_type":"CardBinaryOperatorNode",' +
		'"n":2.0,"e":1e-05}';
	const out = applyTagAliases(withFloat);
	expect(out).toContain('"rhs":["fire"]');
	expect(out).toContain('"n":2.0');
	expect(out).toContain('"e":1e-05');
});

test("the number-spelling reconciliation is narrow: only queries that spell a number Python re-spells", () => {
	let reconciled = 0;
	for (const file of fixtureFiles) {
		for (const c of JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[]) {
			if (c.tree === undefined) continue;
			const tree = canonicalStringify(parseScryfallQuery(c.query, TAG_ALIASES));
			const expected = PORT_ONLY_TREES.get(c.query) ?? applyTagAliases(c.tree);
			if (tree === expected) continue;
			reconciled += 1;
			expect(RESPELLED_NUMBER.test(c.query), `${c.query} differs for another reason`).toBe(true);
		}
	}
	// 13 fuzz fixtures on 2026-09-25 (`artist:007`, `type<2024-02-29`, ...). None is a corpus query.
	expect(reconciled).toBeGreaterThan(0);
	expect(reconciled).toBeLessThan(30);
});

test("a number inside a text value keeps its spelling", () => {
	const value = (q: string) =>
		(JSON.parse(canonicalStringify(parseScryfallQuery(q))) as { kwargs: { rhs: { kwargs: { value: string } } } }).kwargs
			.rhs.kwargs.value;
	// Doubling Cube: the `0796` piece is a NUMBER token, and it lost its zero.
	expect(value("oracleid:9afd8f12-0796-4500-aaa3-10b4a46ef6ec")).toBe("9afd8f12-0796-4500-aaa3-10b4a46ef6ec");
	// A leading all-digit piece, and a trailing one.
	expect(value("oracleid:00037840-6089-42ec-8c5c-281f9f474504")).toBe("00037840-6089-42ec-8c5c-281f9f474504");
	expect(value("oracleid:5c58353a-fd60-4528-bf0d-000000000001")).toBe("5c58353a-fd60-4528-bf0d-000000000001");
	expect(value("a:007")).toBe("007");
	expect(value("o:1.50")).toBe("1.50");
	// A number that is a NUMBER is still one.
	expect(canonicalStringify(parseScryfallQuery("cmc=007"))).toContain('"value":7}');
});

test("every port-only tree names a fixture that exists and still disagrees with it", () => {
	const byQuery = new Map<string, FixtureCase>();
	for (const file of fixtureFiles) {
		for (const c of JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[]) {
			byQuery.set(c.query, c);
		}
	}
	for (const [query, tree] of PORT_ONLY_TREES) {
		const fixture = byQuery.get(query);
		expect(fixture?.tree, `${query} should still be an exported fixture with a tree`).toBeDefined();
		expect(fixture?.tree, `${query}: the vendored parser agrees now — drop the port-only entry`).not.toBe(tree);
	}
});

test("fixture corpus is present and substantial", () => {
	expect(fixtureFiles.length).toBeGreaterThan(0);
	const total = fixtureFiles
		.map((f) => (JSON.parse(readFileSync(join(FIXTURES_DIR, f), "utf-8")) as FixtureCase[]).length)
		.reduce((a, b) => a + b, 0);
	expect(total).toBeGreaterThan(500);
});

for (const file of fixtureFiles) {
	const cases = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as FixtureCase[];
	describe(file, () => {
		for (const fixture of cases) {
			test(`parses ${JSON.stringify(fixture.query)} identically`, () => {
				if (fixture.tree !== undefined) {
					const tree = canonicalStringify(parseScryfallQuery(fixture.query, TAG_ALIASES));
					const expected = PORT_ONLY_TREES.get(fixture.query) ?? applyTagAliases(fixture.tree);
					expect(tree === expected ? tree : pythonNumberSpelling(tree)).toBe(expected);
				} else if (fixture.error !== undefined) {
					let thrown: unknown;
					try {
						parseScryfallQuery(fixture.query, TAG_ALIASES);
					} catch (exc) {
						thrown = exc;
					}
					if (fixture.error.type === "QueryBudgetExceeded") {
						// The budget's user-facing message is a fixed constant on both sides — it
						// deliberately says nothing about WHICH bound was hit — so it compares exactly.
						expect(thrown).toBeInstanceOf(QueryBudgetExceeded);
						expect((thrown as Error).message).toBe(fixture.error.message);
					} else if (fixture.error.type === "InvalidRegexPatternError") {
						// TYPE ONLY. The reason is quoted from whichever regex parser read the
						// pattern — CPython's `sre` upstream, V8's `RegExp` here — and the two
						// describe the same malformed pattern in different words ("missing ),
						// unterminated subpattern" vs "Unterminated group"). Pinning the sentence
						// would pin V8's wording, which is not a property of this port.
						expect(thrown).toBeInstanceOf(InvalidRegexPatternError);
					} else {
						// Python surfaces every remaining failure as ValueError; the port surfaces
						// ParseError with the identical message.
						expect(fixture.error.type).toBe("ValueError");
						expect(thrown).toBeInstanceOf(ParseError);
						expect((thrown as ParseError).message).toBe(fixture.error.message);
					}
				} else {
					throw new Error(`fixture entry for ${JSON.stringify(fixture.query)} has neither tree nor error`);
				}
			});
		}
	});
}
