/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const autocomplete: (a: number, b: number, c: number) => [number, number, number, number];
export const begin_store_load: (a: number) => [number, number];
export const card_by_external_id: (a: number, b: number, c: bigint, d: number, e: number) => [number, number, number, number];
export const card_by_illustration_id: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const card_by_scryfall_id: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const cards_by_scryfall_ids: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const cards_containing_all_words: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const catalog: () => [number, number, number, number];
export const collection_cards_by_names: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const collection_name_ranks: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const exact_card_by_name: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const exact_name_rank: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const fetch_rows: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const finish_store_load: () => [number, number];
export const fuzzy_candidates: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const fuzzy_card_by_name: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const init_store: (a: number, b: number) => [number, number];
export const printings_of_oracle_id: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const query: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const query_keys: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const query_rows: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const query_widens: (a: number, b: number, c: number, d: number) => [number, number, number];
export const random_search: (a: number, b: bigint, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const scryfall_card_from_row: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const scryfall_search: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const sort_key_version: () => number;
export const store_load_chunk: (a: number, b: number) => [number, number];
export const store_loaded: () => number;
export const store_version: () => number;
export const card_count: () => number;
export const size: () => number;
export const unload_store: () => void;
export const __init_panic_hook: () => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
